# Настройки плагина InvSee++
settings:
  # Разрешить игрокам просматривать инвентарь других игроков
  allow_inventory_view: true
  # Разрешить игрокам редактировать инвентарь других игроков
  allow_inventory_edit: false
  # Разрешить игрокам просматривать конечность других игроков
  allow_enderchest_view: true
  # Разрешить игрокам редактировать конечность других игроков
  allow_enderchest_edit: false
